import Menu from "@/components/Menu";
import Navbar from "@/components/Navbar";
import { Toaster } from "@/components/ui/sonner";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Requisite App",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="h-screen flex flex-col">
      <div className="fixed top-0 left-0 w-full z-10">
        <Navbar />
      </div>

      <div className="flex flex-1 pt-[64px]"> 
        
        <div className="fixed top-[64px] left-0 h-[calc(100vh-64px)] w-[14%] md:w-[8%] lg:w-[16%] xl:w-[14%] border-r border-[#e5e5e5] bg-[#0F1E7A]">
          <Menu />
        </div>

        <div className="ml-[14%] md:ml-[8%] lg:ml-[16%] xl:ml-[14%] w-full bg-[#F7F8FA] overflow-y-auto">
          {children}
          <Toaster />
        </div>
      </div>
    </div>
  );
}
