import type { Metadata } from "next";
import { AppSidebar } from "@/components/app-sidebar";
import { SiteHeader } from "@/components/site-header";
import { SidebarInset, SidebarProvider } from "@/components/ui/sidebar";

// import Navbar from "@/components/Navbar";
// import { Menu as MenuIcon } from "lucide-react";
// import {
//   Sheet,
//   SheetContent,
//   SheetTitle,
//   SheetTrigger,
// } from "@/components/ui/sheet";

export const metadata: Metadata = {
  title: "Dashboard - Requisite App",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SidebarProvider
      style={
        {
          "--sidebar-width": "calc(var(--spacing) * 56)",
          "--header-height": "calc(var(--spacing) * 14)",
        } as React.CSSProperties
      }
    >
      <AppSidebar />
      <SidebarInset className="min-w-0">
        <SiteHeader />
        <div className="flex flex-1 flex-col bg-[#F7F8FA] overflow-y-auto">
          {children}
        </div>
      </SidebarInset>
    </SidebarProvider>

    // Old shell (replaced by SidebarProvider above):
    // <div className="h-screen flex flex-col">
    //   <div className="fixed top-0 left-0 w-full z-10">
    //     <Navbar />
    //   </div>
    //   <div className="flex flex-1 pt-16">
    //     <div className="hidden md:flex fixed top-16 left-0 h-[calc(100vh-64px)] w-[14%] border-r border-[#e5e5e5] bg-[#0F1E7A]">
    //       <Menu />
    //     </div>
    //     <div className="flex md:hidden fixed top-[22px] left-4 z-20">
    //       <Sheet>
    //         <SheetTrigger>
    //           <MenuIcon color="white" size={28} />
    //         </SheetTrigger>
    //         <SheetContent side="left" className="bg-[#0F1E7A]! text-white! pt-10 w-[260px] flex flex-col">
    //           <SheetTitle className="sr-only">Dashboard navigation</SheetTitle>
    //           <div className="flex-1 overflow-y-auto">
    //             <Menu />
    //           </div>
    //         </SheetContent>
    //       </Sheet>
    //     </div>
    //     <div className="ml-0 md:ml-[14%] w-full bg-[#F7F8FA] overflow-y-auto">
    //       {children}
    //     </div>
    //   </div>
    // </div>
  );
}
